"""empty message

Revision ID: 0d61c7f90123
Revises: f3a35bb13551
Create Date: 2022-04-14 11:17:10.633066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d61c7f90123'
down_revision = 'f3a35bb13551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('image', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'image')
    # ### end Alembic commands ###
