"""empty message

Revision ID: 71d61978384d
Revises: 1b1558824c02
Create Date: 2022-04-14 10:27:49.647437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d61978384d'
down_revision = '1b1558824c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('breed', sa.String(length=64), nullable=False))
    op.add_column('pets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('pets', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint('pets_owner_fkey', 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'])
    op.drop_column('pets', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key('pets_owner_fkey', 'pets', 'users', ['owner'], ['id'])
    op.alter_column('pets', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('pets', 'user_id')
    op.drop_column('pets', 'breed')
    # ### end Alembic commands ###
