"""empty message

Revision ID: f3a35bb13551
Revises: 71d61978384d
Create Date: 2022-04-14 10:38:50.152036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a35bb13551'
down_revision = '71d61978384d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('image', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'image')
    # ### end Alembic commands ###
